version: '3.9'
services:

  #Orders
#  nf-orders:
#    container_name: orders-service
#    image: fjrd/orders-servicer:0.0.1
#    depends_on:
#      - kafka
#      - postgres-orders
#      #redis
#    ports:
#    - 8081:8081
#    environment:
#      - POSTGRES_URL=jdbc:postgresql://postgres-orders:5433/postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - SERVER_PORT=8081
#    command: [ 'java', '-jar', '/app.jar' ]


 #Processors
#  nf-processor:
#    container_name: processor-service
#    image: fjrd/processor-servicer:0.0.1
#    depends_on:
#      - kafka
#    ports:
#    - 8085:8085
#    command: [ 'java', '-jar', '/app.jar' ]


  #Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: nf-zookeeper
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka
    container_name: nf-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPIC=orders

  #Orders DataBase
  postgres-orders:
    container_name: nf-postgres-orders
    image: postgres:alpine3.14
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - pg-customers-data:/var/lib/postgresql/data/

  #Customers DataBase
  postgres-customers:
    container_name: nf-postgres-customers
    image: postgres:alpine3.14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - pg-orders-data:/var/lib/postgresql/data/

volumes:
  pg-orders-data:
  pg-customers-data:
