version: '3.9'
services:

#  maven:
#    image: maven:3.8.1-openjdk-17
#    volumes:
#    - mvn-cache:/home/.m2

#  #ApiGateway
#  gateway:
#    container_name: nf-api-gateway-service
#    image: ryzhkov/nf-api-gateway-service:0.0.1
#    build:
#      context: gateway_api
#    ports:
#      - 8083:8083
#    environment:
#      - SERVER_PORT=8083
#      - CUSTOMERS_HOST=nf-customers-service
#      - CUSTOMERS_PORT=8091
#      - ORDERS_HOST=nf-orders-service
#      - ORDERS_PORT=8081
#    command: [ 'java', '-jar', '/app.jar' ]
#
#  #Customers
#  customers:
#    container_name: nf-customers-service
#    image: ryzhkov/nf-customers-service:0.0.1
#    build:
#      context: customer_service
#    depends_on:
#      - postgres-customers
#    ports:
#      - 8091:8091
#    environment:
#      - POSTGRES_URL=jdbc:postgresql://nf-postgres-customers:5432/postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - SERVER_PORT=8091
#    command: [ 'java', '-jar', '/app.jar' ]

#  #Shared library
#  shared:
#    container_name: nf-shared
#    image: fjrd/nf-share-library:0.0.1
#    build:
#      context: shared-order-dto
#    volumes:
#      - mvn-cache:/root/.m2
#  #      - "${HOME}/.m2:/root/.m2"

  #Orders
  orders:
    container_name: nf-orders-service
    image: fjrd/nf-orders-service:0.0.1
    build:
      context: orders-service
    depends_on:
#      - shared
      - kafka
      - postgres-orders
      - redis
    ports:
    - 8081:8081
    environment:
      - SERVER_PORT=8081
      - POSTGRES_URL=jdbc:postgresql://nf-postgres-orders:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - KAFKA_HOST_NAME=nf-kafka:9092
      - REDIS_HOST=nf-redis
      - REDIS_PORT=6379
#    volumes:
#      - mvn-cache:/root/.m2
#      - "${HOME}/.m2:/root/.m2"


  processor:
    container_name: nf-processor-service
    image: fjrd/nf-processor-service:0.0.1
    build:
      context: processor-service
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST_NAME=nf-kafka:9092

  #Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: nf-zookeeper
    expose:
      - 2181

  kafka:
    image: wurstmeister/kafka
    container_name: nf-kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=nf-kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPIC=orders
    restart: unless-stopped

  #Redis
  redis:
    container_name: nf-redis
    image: redis:alpine
    ports:
      - 6379:6379

  #Orders DataBase
  postgres-orders:
    container_name: nf-postgres-orders
    image: postgres:alpine3.14
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - pg-customers-data:/var/lib/postgresql/data/

  #Customers DataBase
  postgres-customers:
    container_name: nf-postgres-customers
    image: postgres:alpine3.14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - pg-orders-data:/var/lib/postgresql/data/

volumes:
#  mvn-cache:
  pg-orders-data:
  pg-customers-data:
