spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    drop-first: true

  redis:
    host: ${REDIS_HOST:nf-redis}
    port: ${REDIS_PORT:6379}

  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: analyzer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
