application:
  ordersHost: ${ORDERS_HOST:http://localhost:8081/}
  customersHost: ${CUSTOMERS_HOST:http://localhost:8092/}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

#restUri: http://localhost:8090/auth
restUri: ${CUSTOMERS_HOST:http://localhost:8092}/auth

jwt:
  secret: "spring"
  expiration: 604800

#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka