orders:
  host: http://${ORDERS_HOST:localhost}:${ORDERS_PORT:8081}/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

#restUri: http://localhost:8090/auth
restUri: http://${CUSTOMERS_HOST:localhost}:${CUSTOMERS_PORT:8092}/auth

jwt:
  secret: "spring"
  expiration: 604800

#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka